local radio = dofile("tests/edgetx_distance_fixture.lua")
local count = 0
local function eq(a,b) assert(a == b, "expected " .. tostring(b) .. ", got " .. tostring(a)) end
local function test(name, fn) fn(); count=count+1; print("ok - "..name) end
local function active(mode)
  local r=radio(); r:begin(); r:arm(mode or "D")
  r:set(1,80,true,nil,nil,mode == "Y" and 0 or 30,mode ~= "Y")
  eq(r.output[1],80); return r
end

test("manual never enables on startup and peers are distinct",function()
  for _,sc in ipairs({-1024,1024}) do
    local r=radio({sc=sc}); r:step("AB1 abc012ef\n"); eq(r:latestStatus().session,"00000000")
    r:begin(); r:set(1,80,true,nil,nil,30,true)
    eq(r.output[1],0); eq(r.output[5],0); eq(r:latestStatus().mode,"N")
  end
end)
test("separate yaw and distance modes and full bounds",function()
  local y=active("Y"); eq(y.output[5],0); eq(y.output[6],0); eq(y:latestStatus().mode,"Y")
  y:set(2,80,true,nil,nil,1,true); eq(y:latestStatus().sequence,1)
  local d=active(); eq(d.output[5],30); eq(d.output[6],1024); eq(d:latestStatus().mode,"D")
  d:set(2,-205,true,nil,nil,-51,true); eq(d.output[1],-205); eq(d.output[5],-51)
  d:set(3,205,true,nil,nil,52,true); eq(d:latestStatus().sequence,1) -- no periodic status emitted yet
  eq(d.output[5],-51)
end)
test("distance freshness may withdraw pitch independently",function()
  local r=active(); r:set(2,60,true,nil,nil,0,false)
  eq(r.output[1],60); eq(r.output[2],1024); eq(r.output[5],0); eq(r.output[6],0)
  r:set(3,0,false); eq(r.output[1],0); eq(r.output[2],0); eq(r.output[6],0)
  r:set(4,0,true,nil,nil,0,true); eq(r.output[2],1024); eq(r.output[6],1024)
end)
test("invalid yaw cannot sneak in pitch and stale sequence cannot overwrite",function()
  local r=active(); r:set(2,0,false,nil,nil,1,true); eq(r.output[5],30)
  r:set(1,50,true,nil,nil,-10,true); eq(r.output[5],30)
  r:set(2,0,true,nil,nil,1,false); eq(r.output[5],30)
end)
test("direct enabled mode changes withdraw and require middle",function()
  local r=active(); local before=r:latestStatus().generation
  r.sc=-1024; r:step(); eq(r.output[1],0); eq(r.output[5],0)
  eq(r:latestStatus().mode,"N"); assert(r:latestStatus().generation>before)
  r:step(nil,10); eq(r:latestStatus().state,"M")
  r:arm("Y"); r:set(2,70); eq(r.output[1],70); eq(r.output[6],0)
end)
test("ANGLE exit and unsupported start require manual rearm",function()
  local r=active(); r.sb=0; r:step(); eq(r:latestStatus().state,"F"); eq(r.output[6],0)
  r.sb=-1024; r:step(); eq(r:latestStatus().state,"F")
  r:arm("D"); r:set(2,80,true,nil,nil,30,true); eq(r.output[5],30)
  r.ele=200; r.sc=0; r:step(); r.sc=1024; r:step(); eq(r:latestStatus().state,"M")
end)
test("every stick amplitude temporarily releases only its own axis",function()
  for _,axis in ipairs({"rud","ele"}) do
    for _,amplitude in ipairs({103,257,513,1024,-1024}) do
      local r=active(); local initial=r:latestStatus()
      local phase=axis == "rud" and "yawPhase" or "pitchPhase"
      local output=axis == "rud" and 1 or 5
      local other=axis == "rud" and 5 or 1
      r[axis]=amplitude
      local hb=r.output[4]
      for i=1,30 do
        r:set(i+1,80,true,i*10,nil,30,true)
        eq(r:latestStatus().state,"A"); eq(r:latestStatus()[phase],"M")
        eq(r.output[output],0); eq(r.output[output+1],0)
        eq(r.output[other],axis == "rud" and 30 or 80)
        eq(r.output[other+1],1024)
        eq(r.output[4],-hb); hb=r.output[4]
        eq(r:latestStatus().generation,initial.generation)
        eq(r:latestStatus().session,initial.session)
      end
      r[axis]=0; r:set(32,80,true,310,nil,30,true)
      r:set(33,80,true,320,nil,30,true)
      local old=r:latestStatus(); r:set(34,80,true,330,old,30,true)
      eq(r:latestStatus()[phase],"R"); eq(r.output[output+1],0)
      r:set(35,80,true,331,nil,30,true)
      eq(r:latestStatus()[phase],"A"); eq(r.output[output+1],1024)
      eq(r:latestStatus().generation,initial.generation)
    end
  end
end)
test("lease expiry still withdraws both outputs",function()
  local e=active(); e:step(nil,30); eq(e:latestStatus().cause,"E")
  eq(e.output[1],0); eq(e.output[5],0)
  e:step(nil,100); eq(e:latestStatus().state,"F")
end)
test("tickets expire on original issue and reconnect fences old commands",function()
  local r=active(); local old=r:latestStatus(); r:step(nil,31)
  r:set(2,90,true,nil,old,30,true); eq(r.output[6],0)
  r:begin("12345678"); r:set(3,90,true,nil,old,30,true); eq(r.output[6],0)
  r:step(nil,32); eq(r:latestStatus().state,"M")
end)
test("queued and oversized data fault before publishing multiple outputs",function()
  local r=active(); r:step(string.rep("x",97).."\n"); eq(r.output[6],0); eq(r:latestStatus().cause,"O")
  local q=active(); q:step(string.rep("x",384)); eq(q.output[6],0); eq(q:latestStatus().state,"F")
end)
test("two accepted queued commands publish newest once",function()
  local r=active(); local hb=r.output[4]
  r:step(r:command(2,20,true,nil,10,true)..r:command(3,30,true,nil,-10,true))
  eq(r.output[1],30); eq(r.output[5],-10); eq(r.output[4],-hb)
end)
test("clock wrap supports pitch leases with Lua32 integers",function()
  local r=radio({now=2147483630}); r:begin(); r:arm("D"); r:set(1,80,true,nil,nil,30,true)
  r:step(nil,-2147483646); eq(r.output[6],1024)
  r:step(nil,-2147483636); eq(r.output[6],0)
end)
test("malformed peripheral and clock states withdraw all six outputs",function()
  for _,change in ipairs({function(r) r.ele=nil end,function(r) r.sb=99 end,
      function(r) r.name="ARGOS FLY" end,function(r) r.flip=1024 end,
      function(r) r.clockError=true end,function(r) r.readError=true end}) do
    local r=active(); change(r); r:step(); eq(r.output[1],0); eq(r.output[5],0); eq(r.output[6],0)
  end
end)

test("V3 refuses previous distance protocols",function()
  local r=radio(); r:step("DB1 abc012ef\n")
  eq(r:latestStatus().session,"00000000")
  r:step("DB2 abc012ef\n"); eq(r:latestStatus().session,"00000000")
  eq(r.writes[1],"ARGOS_DISTANCE_STREAM_V3\n")
  r:begin(); r:arm("D"); r:set(1,80,true,nil,nil,30,true)
  r:step((r:command(2,90,true,nil,-40,true):gsub("^DS3 ","DS2 ")))
  eq(r.output[1],80); eq(r.output[5],30)
end)
test("gentle Ele releases only pitch and restores the original stream",function()
  for _,ele in ipairs({103,180,-180,256}) do
    local r=active(); local generation=r:latestStatus().generation
    r.ele=ele; r:set(2,60,true,5,nil,40,true)
    eq(r.output[1],60); eq(r.output[2],1024); eq(r.output[5],0); eq(r.output[6],0)
    eq(r:latestStatus().state,"A"); eq(r:latestStatus().pitchPhase,"M")
    r:set(3,65,true,15,nil,35,true)
    eq(r.output[1],65); eq(r.output[6],0)
    r.ele=0; r:set(4,70,true,20,nil,32,true)
    r:set(5,70,true,30,nil,32,true)
    local beforeBarrier=r:latestStatus()
    r:set(6,70,true,40,beforeBarrier,32,true)
    eq(r.output[1],70); eq(r.output[6],0); eq(r:latestStatus().pitchPhase,"R")
    eq(r:latestStatus().generation,generation)
    r:set(7,70,true,41,nil,-20,true)
    eq(r.output[1],70); eq(r.output[5],-20); eq(r.output[6],1024)
    eq(r:latestStatus().pitchPhase,"A"); eq(r:latestStatus().generation,generation)
  end
end)
test("fresh yaw commands cannot smuggle pitch across the recenter barrier",function()
  local r=active(); r.ele=150; r:set(2,60,true,5,nil,45,true)
  r.ele=0; r:set(3,60,true,10,nil,45,true)
  r:set(4,60,true,20,nil,45,true); local old=r:latestStatus()
  r:set(5,60,true,30,old,45,true)
  local current=r:latestStatus(); eq(current.pitchPhase,"R")
  r:step(r:command(6,70,true,old,45,true)..r:command(7,75,true,old,-45,true),31)
  eq(r.output[1],75); eq(r.output[5],0); eq(r.output[6],0)
  r:set(8,75,true,32,current,0,false)
  eq(r.output[6],0); eq(r:latestStatus().pitchPhase,"R")
  r:set(9,75,true,33,current,-35,true)
  eq(r.output[5],-35); eq(r.output[6],1024); eq(r:latestStatus().pitchPhase,"A")
end)
test("partial recenter restarts its full hysteresis dwell",function()
  local r=active(); r.ele=150; r:set(2,60,true,5,nil,40,true)
  r.ele=0; r:set(3,60,true,10,nil,40,true)
  r.ele=52; r:set(4,60,true,20,nil,40,true)
  r.ele=0; r:set(5,60,true,25,nil,40,true)
  r:set(6,60,true,35,nil,40,true)
  r:set(7,60,true,44,nil,40,true)
  eq(r:latestStatus().pitchPhase,"M"); eq(r.output[6],0)
  r:set(8,60,true,45,nil,40,true)
  eq(r:latestStatus().pitchPhase,"R"); eq(r.output[6],0)
  -- Leaving the centered band while waiting for a fresh ticket starts over.
  local queued=r:latestStatus(); r.ele=60; r:set(9,60,true,46,queued,40,true)
  eq(r:latestStatus().pitchPhase,"M"); eq(r.output[6],0)
  r.ele=0; r:set(10,60,true,50,nil,40,true)
  r:set(11,60,true,60,nil,40,true); r:set(12,60,true,70,nil,40,true)
  eq(r:latestStatus().pitchPhase,"R"); eq(r.output[6],0)
  r:set(13,60,true,71,nil,40,true)
  eq(r.output[5],40); eq(r:latestStatus().pitchPhase,"A")
end)
test("temporary manual retains transport expiry and failures",function()
  local r=active(); r.ele=150; r:set(2,60,true,5,nil,40,true)
  local old=r:latestStatus(); r:step(nil,35)
  eq(r.output[1],0); eq(r.output[6],0); eq(r:latestStatus().cause,"E")
  r.ele=0; r:set(3,60,true,40,old,40,true)
  eq(r.output[1],0); eq(r.output[6],0)
  r:step(nil,105); eq(r:latestStatus().state,"F"); eq(r:latestStatus().pitchPhase,"N")
  local n=active(); n.ele=1024; n.rud=-1024; n:step(nil,5); n.readError=true; n:step(nil,10)
  eq(n:latestStatus().cause,"I"); eq(n:latestStatus().mode,"N"); eq(n.output[2],0); eq(n.output[6],0)
end)
test("target loss during gentle manual cannot invent pitch authority",function()
  local r=active(); r.ele=150; r:set(2,60,true,5,nil,40,true)
  r:set(3,0,false,10); eq(r.output[6],0); eq(r:latestStatus().pitchPhase,"M")
  r.ele=0; r:set(4,0,false,15); r:set(5,0,false,25); r:set(6,0,false,35)
  eq(r.output[6],0); eq(r:latestStatus().pitchPhase,"R")
  r:set(7,60,true,36,nil,0,false)
  eq(r.output[1],60); eq(r.output[6],0); eq(r:latestStatus().pitchPhase,"R")
  r:set(8,60,true,40,nil,-30,true)
  eq(r.output[5],-30); eq(r:latestStatus().pitchPhase,"A")
end)
test("recenter barrier compares signed clock wrap with integer arithmetic",function()
  local base=2147483630
  local function at(delta)
    local n=base+delta
    if n>2147483647 then n=n-2147483647-2147483647-2 end
    return n
  end
  local r=radio({now=base}); r:begin(); r:arm("D"); r:set(1,80,true,nil,nil,30,true)
  r.ele=150; r:set(2,60,true,at(5),nil,40,true)
  r.ele=0; r:set(3,60,true,at(10),nil,40,true)
  r:set(4,60,true,at(20),nil,40,true); local old=r:latestStatus()
  r:set(5,60,true,at(30),old,40,true)
  eq(r:latestStatus().pitchPhase,"R"); eq(r.output[6],0)
  r:set(6,60,true,at(31),old,40,true); eq(r.output[6],0)
  r:set(7,60,true,at(32),nil,40,true)
  eq(r.output[5],40); eq(r:latestStatus().pitchPhase,"A")
end)


test("both axes recover independently without selecting another target",function()
  local r=active(); local generation=r:latestStatus().generation
  r.ele=1024; r.rud=-1024; r:set(2,80,true,5,nil,30,true)
  eq(r.output[2],0); eq(r.output[6],0)
  eq(r:latestStatus().yawPhase,"M"); eq(r:latestStatus().pitchPhase,"M")
  r.ele=0; r:set(3,80,true,10,nil,30,true)
  r:set(4,80,true,20,nil,30,true); r:set(5,80,true,30,nil,30,true)
  eq(r:latestStatus().pitchPhase,"R"); eq(r.output[6],0)
  r:set(6,80,true,31,nil,30,true)
  eq(r.output[2],0); eq(r.output[5],30); eq(r.output[6],1024)
  r.rud=0; r:set(7,80,true,35,nil,30,true)
  r:set(8,80,true,45,nil,30,true); local old=r:latestStatus()
  r:set(9,80,true,55,old,30,true)
  eq(r.output[2],0); eq(r.output[6],1024); eq(r:latestStatus().yawPhase,"R")
  r:set(10,80,true,56,old,30,true); eq(r.output[2],0)
  r:set(11,80,true,56,nil,30,true)
  eq(r.output[1],80); eq(r.output[2],1024); eq(r.output[6],1024)
  eq(r:latestStatus().generation,generation)
end)
test("yaw-only Ele is always manual while full Rud recovers without SC",function()
  local r=active("Y"); r.ele=1024
  for i=1,10 do
    r:set(i+1,80,true,i*10,nil,0,false)
    eq(r.output[1],80); eq(r.output[2],1024); eq(r:latestStatus().pitchPhase,"N")
  end
  r.rud=1024; r:set(12,80,true,105,nil,0,false)
  eq(r.output[2],0); eq(r:latestStatus().yawPhase,"M")
  r.rud=0; r:set(13,80,true,110,nil,0,false)
  r:set(14,80,true,120,nil,0,false); r:set(15,80,true,130,nil,0,false)
  eq(r.output[2],0); eq(r:latestStatus().yawPhase,"R")
  r:set(16,80,true,131,nil,0,false)
  eq(r.output[1],80); eq(r.output[2],1024); eq(r.output[6],0)
end)
test("SC middle overrides both temporary manual axes and needs physical enable",function()
  local r=active(); r.ele=1024; r.rud=-1024; r:set(2,80,true,5,nil,30,true)
  local old=r:latestStatus(); r.sc=0; r:set(3,80,true,10,old,30,true)
  eq(r:latestStatus().mode,"N"); eq(r:latestStatus().yawPhase,"N")
  eq(r:latestStatus().pitchPhase,"N"); eq(r.output[2],0); eq(r.output[6],0)
  r.ele=0; r.rud=0; r:set(4,80,true,20,old,30,true)
  eq(r.output[2],0); eq(r.output[6],0)
  r:arm("D"); r:set(5,80,true,nil,nil,30,true)
  eq(r.output[2],1024); eq(r.output[6],1024)
end)
test("invalid observations cannot renew either overridden axis after recenter",function()
  local r=active(); r.rud=1024; r.ele=1024; r:set(2,80,true,5,nil,30,true)
  r.rud=0; r.ele=0; r:set(3,0,false,10); r:set(4,0,false,20); r:set(5,0,false,30)
  eq(r:latestStatus().yawPhase,"R"); eq(r:latestStatus().pitchPhase,"R")
  r:set(6,0,false,31); eq(r.output[2],0); eq(r.output[6],0)
  eq(r:latestStatus().yawPhase,"R"); eq(r:latestStatus().pitchPhase,"R")
  r:set(7,80,true,32,nil,0,false)
  eq(r.output[2],1024); eq(r.output[6],0)
  eq(r:latestStatus().yawPhase,"A"); eq(r:latestStatus().pitchPhase,"R")
  r:set(8,80,true,33,nil,30,true); eq(r.output[6],1024)
end)


test("both fully displaced sticks keep fresh heartbeat without any amplitude latch",function()
  local r=active(); local generation=r:latestStatus().generation; local hb=r.output[4]
  r.rud=1024; r.ele=-1024
  for i=1,30 do
    r:set(i+1,80,true,i*10,nil,-30,true)
    eq(r.output[2],0); eq(r.output[6],0); eq(r.output[4],-hb); hb=r.output[4]
    eq(r:latestStatus().state,"A"); eq(r:latestStatus().generation,generation)
    eq(r:latestStatus().yawPhase,"M"); eq(r:latestStatus().pitchPhase,"M")
  end
end)
test("same-clock reads still distinguish old tickets from post-barrier tickets",function()
  local r=active(); r.rud=1024; r.ele=1024; r:set(2,80,true,5,nil,30,true)
  r.rud=0; r.ele=0; r:set(3,80,true,10,nil,30,true)
  r:set(4,80,true,20,nil,30,true); local old=r:latestStatus()
  r:set(5,80,true,30,old,30,true); local new=r:latestStatus()
  eq(r.output[2],0); eq(r.output[6],0)
  r:set(6,80,true,30,old,30,true); eq(r.output[2],0); eq(r.output[6],0)
  r:set(7,80,true,30,new,30,true); eq(r.output[2],1024); eq(r.output[6],1024)
end)

print("passed "..count.." distance Lua tests")
